# Generated by Django 2.2 on 2019-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('row_start', models.IntegerField()),
                ('row_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaginationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('rows', models.IntegerField()),
            ],
        ),
    ]
