# Generated by Django 2.2 on 2019-04-24 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_id', models.CharField(max_length=19, unique=True)),
                ('sequence', models.CharField(max_length=80, null=True)),
                ('kingdom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='biology.Kingdom')),
                ('specie', models.ManyToManyField(related_name='entry', to='biology.Specie')),
            ],
        ),
    ]
